### ISSUE TITLE
Splice Sprite Nodes Do Not Evaluate When Opening a File

### ISSUE THREAD

**Issue by Synthoid** [Ttanasart-pt/Pixel-Composer#13] opened 2022-12-27 04:49 UTC
When opening an existing `.pxc` file, some nodes do not automatically evaluate and generate their expected outputs. I've noticed this with the `Splice Sprite` node specifically. Minimizing and refocusing the application seems to fix the issue, as does adjusting a value on the affected node. This was seen on `v. 1.0.6`.

*Expected:*
![image](https://user-images.githubusercontent.com/6645950/209612226-608ca616-96d1-4141-9243-f098fd717577.png)

*Error:*
![image](https://user-images.githubusercontent.com/6645950/209612074-4caf3c17-861e-4a89-8111-1c345de2d8d8.png)

**Comment by Ttanasart-pt** [comment] 2022-12-27 11:57
I checked it, and it was caused by some hack I use for the preview gizmo. 

The fix will be included in version 1.0.8. Thank you for reporting in!

**Closed by Ttanasart-pt** 2022-12-27 11:57 UTC
